


export const GET_TODOS_REQUEST="GET_TODOS_REQUEST";
export const GET_TODOS_ERROR="GET_TODOS_ERROR";
export const GET_TODOS_SUCCESS="GET_TODOS_SUCCESS";


export const GET_TODOS="GET_TODOS";
export const DELETE_TODO="DELETE_TODO";
export const SINGLE_TODO="SINGLE_TODO";


export const GET_TODOS_SUCCESS1="GET_TODOS_SUCCESS1"


export const ADD_TODO_REQUEST='ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS='ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE='GET_TODO_FAILURE';


export const DELETE_TODO_SUCCESS="DELETE_TODO_SUCCESS"
export const DELETE_TODO_FAILURE="DELETE_TODO_FAILURE"

export const UPDATE_TODO_REQUEST='UPDATE_TODO_REQUEST';
export const UPDATE_TODO_SUCCESS='UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILURE='UPDATE_TODO_FAILURE';
